
###add client
POST http://localhost:8080/client/addClient
Content-Type: application/json

{
  "clientName": "test 3",
  "totalMoney": 1234.5
}
###see all clients
GET http://localhost:8080/client/getAllClient
Accept: application/json

###delete a client
DELETE http://localhost:8080/client/deleteById/2

###see 1 client
GET http://localhost:8080/client/getClientById/3
Accept: application/json

###update client
POST http://localhost:8080/client/updateClient/2
Content-Type: application/json

{
  "clientName": "Sasa",
  "totalMoney": 2222.0
}