
###add transactions
POST http://localhost:8080/transactions/addTransactions
Content-Type: application/json

{
  "bankName": "sabs",
  "bankPhoto": "photo",
  "clientId": 1,
  "moneyBank": 100.0
}
###see all transactionss
GET http://localhost:8080/transactions/getAllTransactions
Accept: application/json

###delete a transactions
DELETE http://localhost:8080/transactions/deleteById/2

###see transactions per client id
GET http://localhost:8080/transactions/getTransactionsById/1
Accept: application/json

###update transactions
POST http://localhost:8080/transactions/updateTransactions/2
Content-Type: application/json

{
  "bankMoney": 2222.0
}