FROM maven:3.9-eclipse-temurin-21-alpine  AS build

COPY src /app/src

COPY pom.xml /app

WORKDIR /app

RUN mvn clean install

FROM eclipse-temurin:21

WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar

EXPOSE 8080

CMD ["java","-jar","app.jar"]                                                                       